### ISSUE TITLE
Add nuxt3

### ISSUE THREAD

**Issue by wolfcoder** [qirolab/Ctrl-Alt-Cheat-issues#2]
Please add Nuxt3 in the default library.

**Comment by hkp22** [comment]
@wolfcoder 
Thank you for your suggestion! Including Nuxt 3 in the default library is a great idea, and I appreciate your feedback. I'll work on adding cheat sheets for Nuxt 3 in an upcoming update to the Ctrl+Alt+Cheat extension. Stay tuned, and feel free to share any other suggestions you have!

**Comment by wolfcoder** [comment]
That awesome Kumar .

**Comment by hkp22** [comment]
Nuxt 3 Cheatsheet added into the Ctrl+Alt+Cheat extension

**Comment by wolfcoder** [comment]
Wonderfull Kumar. this is amazing.
